import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JPasswordField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amoah
 */
public class ActionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ActionFrame
     */
    public ActionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
         /* lblTitle = new javax.swing.JLabel();
        lblTitle.setFont(new Font("Times New Roman", Font.BOLD, 64));
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitle.setBounds(12, 13, 675, 144);
        getContentPane().add(lblTitle);

        lblTitle.setText("Team Dragon POS");
         
         */
         
         Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        int framewidth=this.getSize().width;//get the width of the frame
        int frameheigth=this.getSize().height; //get the heigth of the frame
        int framelocationX=(dim.width-framewidth)/2; 
        int framelocationY=(dim.height-frameheigth)/2;
        this.setLocation(framelocationX,framelocationY);
         
         
         
        buttonProcessRental = new javax.swing.JButton();
        buttonManageUsers = new javax.swing.JButton();
        buttonProcessSaleReturn = new javax.swing.JButton();
        buttonProcessRentalReturn = new javax.swing.JButton();
        buttonProcessSale = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
         setTitle("Action View");
         //setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonProcessRental.setText("Process Rental");
        buttonProcessRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessRentalActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        buttonManageUsers.setText("ManageUsers");
        buttonManageUsers.addActionListener(new java.awt.event.ActionListener() {
=======
        buttonManageUsers.setText("Manage Users");
         buttonManageUsers.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> 86ee14ab7b739ee2db2bdeb1d7ae7b06507ac412
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManageUsersActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        buttonProcessSaleReturn.setText("ProcessSaleReturn");
        buttonProcessSaleReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessSaleReturnActionPerformed(evt);
            }
        });

        buttonProcessRentalReturn.setText("ProcessRentalReturn");
        buttonProcessRentalReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
=======
        buttonProcessSaleReturn.setText("Process Sale Return");
        buttonProcessSaleReturn.setText("Process Rental Return");
         buttonProcessSaleReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               System.out.println("");
                buttonProcessSaleReturnActionPerformed(evt);
            }
        });


        buttonProcessRentalReturn.setText("Process Rental Return");
         buttonProcessRentalReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               System.out.println("");
>>>>>>> 86ee14ab7b739ee2db2bdeb1d7ae7b06507ac412
                buttonProcessRentalReturnActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        buttonProcessSale.setText("ProcessSale");
        buttonProcessSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
=======
        buttonProcessSale.setText("Process Sale");
         buttonProcessSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               //System.out.println("");
>>>>>>> 86ee14ab7b739ee2db2bdeb1d7ae7b06507ac412
                buttonProcessSaleActionPerformed(evt);
            }
        });

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
<<<<<<< HEAD
                buttonLogoutActionPerformed(evt);
            }
        });
=======
               //System.out.println("");
                buttonLogoutActionPerformed(evt);
            }
        });

>>>>>>> 86ee14ab7b739ee2db2bdeb1d7ae7b06507ac412

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonManageUsers)
                            .addComponent(buttonProcessRentalReturn)
                            .addComponent(buttonProcessRental)
                            .addComponent(buttonProcessSale)
                            .addComponent(buttonProcessSaleReturn))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonLogout)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(buttonProcessRental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonProcessRentalReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonProcessSale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonProcessSaleReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonManageUsers)
                .addGap(18, 18, 18)
                .addComponent(buttonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProcessRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessRentalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessRentalFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonProcessRentalActionPerformed


     private void buttonManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManageUsersActionPerformed
         // TODO add your handling code here:
         this.dispose();
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new ManageUsersFrame().setVisible(true);
             }
         });
    }//GEN-LAST:event_buttonManageUsersActionPerformed

     private void buttonProcessRentalReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessRentalReturnActionPerformed
         // TODO add your handling code here:
         this.dispose();
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new ProcessRentalReturnFrame().setVisible(true);
             }
         });
    }//GEN-LAST:event_buttonProcessRentalReturnActionPerformed

    private void buttonProcessSaleActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessSaleFrame().setVisible(true);
            }
        });
    }                                                 

    private void buttonProcessSaleReturnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessSaleReturnFrame().setVisible(true);
            }
        });
    }                                                       

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String[] args = {"garbage"};
                LoginGUI.main(args);
            }
        });
    }                                            

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_buttonLogoutActionPerformed

     private void buttonProcessSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessSaleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessSaleGui().setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonProcessSaleActionPerformed
    
      private void buttonProcessSaleReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessSaleReturnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessRentalReturnFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonProcessSaleReturnActionPerformed
    
<<<<<<< HEAD
=======


    

>>>>>>> 86ee14ab7b739ee2db2bdeb1d7ae7b06507ac412
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
     /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*  try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form *//*
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new ActionFrame().setVisible(true);
     }
     });
     }
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonManageUsers;
    private javax.swing.JButton buttonProcessRental;
    private javax.swing.JButton buttonProcessRentalReturn;
    private javax.swing.JButton buttonProcessSale;
    private javax.swing.JButton buttonProcessSaleReturn;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
