import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
/**
 *
 * @author Amoah
 */
public class ActionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ActionFrame
     */
    public ActionFrame() {
    	setTitle("Action Frame");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonProcessRental = new javax.swing.JButton();
        buttonManageUsers = new javax.swing.JButton();
        buttonProcessSaleReturn = new javax.swing.JButton();
        buttonProcessRentalReturn = new javax.swing.JButton();
        buttonProcessSale = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonProcessRental.setText("ProcessRental");
        buttonProcessRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessRentalActionPerformed(evt);
            }
        });

        buttonManageUsers.setText("ManageUsers");
        buttonManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManageUsersActionPerformed(evt);
            }
        });

        buttonProcessSaleReturn.setText("ProcessSaleReturn");
        buttonProcessSaleReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessSaleReturnActionPerformed(evt);
            }
        });

        buttonProcessRentalReturn.setText("ProcessRentalReturn");
        buttonProcessRentalReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessRentalReturnActionPerformed(evt);
            }
        });

        buttonProcessSale.setText("ProcessSale");
        buttonProcessSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessSaleActionPerformed(evt);
            }
        });

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });
        
        JLabel optionLabel = new JLabel("Please select one of the following options:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(481, Short.MAX_VALUE)
        			.addComponent(buttonLogout)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(52)
        			.addComponent(optionLabel)
        			.addContainerGap(302, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(96)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(buttonProcessRentalReturn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(buttonProcessSale, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(buttonProcessRental, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(buttonProcessSaleReturn, GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        				.addComponent(buttonManageUsers, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(optionLabel)
        			.addGap(18)
        			.addComponent(buttonProcessRental)
        			.addGap(18)
        			.addComponent(buttonProcessRentalReturn)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(buttonProcessSale)
        			.addGap(11)
        			.addComponent(buttonProcessSaleReturn)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(26)
        					.addComponent(buttonLogout))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(buttonManageUsers)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProcessRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessRentalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessRentalFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonProcessRentalActionPerformed


     private void buttonManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManageUsersActionPerformed
         // TODO add your handling code here:
         this.dispose();
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 try {
                     new ManageUsersFrame().setVisible(true);
                 } catch (SQLException ex) {
                     Logger.getLogger(ActionFrame.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (IOException ex) {
                     Logger.getLogger(ActionFrame.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (ClassNotFoundException ex) {
                     Logger.getLogger(ActionFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
         });
    }//GEN-LAST:event_buttonManageUsersActionPerformed

     private void buttonProcessRentalReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessRentalReturnActionPerformed
         // TODO add your handling code here:
         this.dispose();
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new ProcessRentalReturnFrame().setVisible(true);
             }
         });
    }//GEN-LAST:event_buttonProcessRentalReturnActionPerformed

    private void buttonProcessSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessSaleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessSaleFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonProcessSaleActionPerformed

    private void buttonProcessSaleReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessSaleReturnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleReturnFrameAK().setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonProcessSaleReturnActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String[] args = {"garbage"};
                LoginGUI.main(args);
            }
        });
    }//GEN-LAST:event_buttonLogoutActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
     /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*  try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(ActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form *//*
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new ActionFrame().setVisible(true);
     }
     });
     }
     */
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonManageUsers;
    private javax.swing.JButton buttonProcessRental;
    private javax.swing.JButton buttonProcessRentalReturn;
    private javax.swing.JButton buttonProcessSale;
    private javax.swing.JButton buttonProcessSaleReturn;
}
